### ISSUE TITLE
hi i have a question ,why MUST have a  usb_p pull-up resistor to usb_pu 

### ISSUE THREAD

**Issue by yangxingquan** [tinyfpga/TinyFPGA-Bootloader#50]
What is the role of the usb_pu to FPAG
4:MUST have a 1.5k pull-up resistor on the USB_P line and SHOULD connect the 1.5K pull-up resistor to the usb_pu signal from the bootloader

**Comment by lolsborn** [comment]
So I'm not an expert so take this with a grain of salt, but it allows the bootloader to pull the USB_P line up indicating it's a "full speed" USB device.

```A USB device must indicate its speed by pulling either the D+ or D- line high to 3.3 volts. A full speed device, pictured below will use a pull up resistor attached to D+ to specify itself as a full speed device.```
From: https://www-user.tu-chemnitz.de/~heha/viewchm.php/hs/usb.chm/usb2.htm

It's tied to a pin on the FPGA instead of directly to 3.3v so your application can choose to enable it or not for your application.

**Comment by yangxingquan** [comment]
@lolsborn  tks very much，may other reason is ,
No USB device, whether bus powered or self powered can drive the VBUS on its upstream facing port. If VBUS is lost, the
device has a lengthy 10 ms to remove power from the D+/D- pull-up resistors used for speed identification
